[tsldb]
index_dir_path = "index"
num_log_messages_threshold = 100000
num_data_points_threshold = 100000

[server]
port = 3000
commit_interval_in_seconds = 30
timestamp_key = "date"

[rabbitmq]
container_name = "infino-queue"
