[tsldb]
index_dir_path = "index"
num_log_messages_threshold = 100000
num_data_points_threshold = 100000

[server]
port = 3000
commit_interval_in_seconds = 30
timestamp_key = "date"
labels_key = "labels"
use_rabbitmq = "no"             # specifies whether to write incoming messages to rabbitmq


# In case the server section specifies to use rabbitmq (use_rabbitmq = yes),
# configuration for rabbitmq needs to be specified. Sample configuration below.
[rabbitmq]
container_name = "infino-queue"
stream_port = 5552
listen_port = 5672
