name: Build and Test

on:
  pull_request:
    branches: [main]

# Skipping TSLDB tests for now
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install minimal stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Build Infino
        run:  cargo build
      # - name: Run Infino tests
      #   run:  cargo test --package infino --bin infino -- tests
